embrace-io/embrace-unity-sdk

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md
Missing contribution guidelines and PR template for community engagement enablement.
Review requested. No code changes.
**WHAT**:<br>Added CONTRIBUTING.md and PULL_REQUEST_TEMPLATE.md
**WHY**:<br>Missing guidelines for contributing to the SDK
**WHO**:<br>All SDK contributors! Best of luck and happy to work with y'all!
=> Adding contribution guidelines

io.embrace.sdk/Scripts/Embrace.cs, io.embrace.sdk/Scripts/Native/Embrace_Android.cs
Making the Unity SDK more defensive in its coding approach. Should help prevent unexpected NPEs
Ran automated test suite.
=> Null guards and mutex edits

io.embrace.sdk/Scripts/Embrace.cs
Try Catch Startup defense added to prevent startup exception based crashes.
=> Startup Try-Catch defense

io.embrace.sdk/CHANGELOG.md, io.embrace.sdk/Resources/Info/EmbraceSdkInfo.json
* Addition of Performance Tracing Support
* Update Embrace Android SDK dependency to 6.8.3
* Update of min Android SDK dependency to 24
* Patch reducing crash rate on SDK startup
=> Version update

README.md
Sorry
**WHAT**:<br>
**WHY**:<br>
**WHO**:<br>
=> Fix readme license link

io.embrace.sdk/CHANGELOG.md, io.embrace.sdk/Resources/Info/EmbraceSdkInfo.json, io.embrace.sdk/package.json
Changelog updates for 2.0.1 to prep for release
=> version info updates for 2.0.1

io.embrace.sdk/Samples/Demo/Scripts/SetupEmbraceDemo.cs
Removed extraneous code leftover from dev
=> Removing extraneous line from Setup

README.md, setup_iOS_build_environment.sh
Build documentation improvement
=> MVP for build documentation

io.embrace.sdk/Editor/EmbracePostBuildProcessor.cs
These cause conflicts with the Swift package manager version of the SDK.
=> Remove Embrace XCFrameworks from previous versions of the SDK

.github/scripts/release.py, .github/workflows/tag_release.yml, io.embrace.sdk/Resources/Info/EmbraceSdkInfo.json, io.embrace.sdk/package.json
This is the working branch for preparing the v2.2.0 release.
=> Release v2.2.0

io.embrace.sdk/CHANGELOG.md
This is out of sync with the one [in the Embrace documentation](https://embrace.io/docs/unity/changelog/).
=> Update changelog to match documentation

io.embrace.sdk/Scripts/Native/Embrace_Android.cs
Patch updating API for Embrace Android 7.x
=> 7.x android payer patch

io.embrace.sdk/Scripts/Native/Embrace_Android.cs
Remap of span functions to combined Unity internal interface
=> patch to Android setup

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
This adds a Code of Conduct file and information regarding contributing to the project.
=> Update readme with notes about contributing

io.embrace.sdk/iOS/EmbraceUnityiOS/.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata, io.embrace.sdk/iOS/EmbraceUnityiOS/Package.resolved, io.embrace.sdk/iOS/EmbraceUnityiOS/Package.swift
Update the native iOS SDK version to fix issues
Automated tests and device build + testing
Updated Embrace iOS SDK from 6.8.0 to 6.8.4 which resolved some issues on iOS
**WHAT**: Update iOS Native SDK<br>
**WHY**: Fix iOS Issues<br>
**WHO**: Ben Bennett<br>
=> Native iOS SDK Update

io.embrace.sdk/Editor/Editor Windows/Installation.cs
Fix issue where non-existent key can cause benign exception on first installation of SDK.
Tested in local exported workspace environments.
Changes are internal and should not affect customers.
=> patch to Installation.cs that covers code closure

.github/workflows/tag_release.yml, io.embrace.sdk/CHANGELOG.md, io.embrace.sdk/Resources/Info/EmbraceSdkInfo.json, io.embrace.sdk/package.json
Updating versioning notes for 2.4.0
No testing required
=> Version Notes Update for 2.4.0

io.embrace.internal/Testing/Edit Mode Tests/AutomaticNetworkCaptureTests.cs, io.embrace.internal/Testing/EmbraceTestMessages.cs, io.embrace.internal/Testing/EmbraceTestMessages.cs.meta, io.embrace.sdk/Scripts/EmbraceMessages.cs, io.embrace.sdk/Scripts/EmbraceMessages.cs.meta, io.embrace.sdk/Scripts/Embrace_Stub.cs, io.embrace.sdk/Scripts/Native/Embrace_Android.cs, io.embrace.sdk/Scripts/Native/Embrace_iOS.cs
Messages should now be consistent between iOS and Android. Also added some missing logs when things might fail (failed string conversion for example).
Messaging consistency and clarity
Automated Testing
Updated messaging to be consistent on both iOS and Android. Moved all error messages to consts within a dedicated file.
**WHAT**:<br>
**WHY**:<br>
**WHO**:Ben Bennett<br>
=> Updated logging

.github/workflows/release.yml
fixed arg name for action uploading SDK version info
**WHAT**:<br>
**WHY**:<br>
**WHO**:<br>
=> fixed arg name for action uploading SDK version info

.github/dependabot.yml, .github/workflows/release.yml
... and some other minor CI housekeeping.
=> chore: pin all 3rd-party GitHub actions

.github/workflows/tag_release.yml
CI update for tag release
CI Test provided by devops
None
=> tag-release patch

io.embrace.sdk/Scripts/EmbraceStandaloneInputModule.cs
Patch to remove serialization flag in editor.
Change viewed in editor
Unnecessary serialization flag for EmbraceStandaloneInputModule.cs removed.
=> Removing unnecessary serialization flag in editor to prevent confusion

io.embrace.internal/Testing/Edit Mode Tests/SettingsManagerTests.cs, io.embrace.internal/Testing/Play Tests/SceneManagerOverrideTests.cs, io.embrace.sdk/Scripts/EmbraceSceneManagerOverride.cs
Changes covering unit test issues
Tested locally and on CI
None
=> Minimum patch change
